version: "2.1"
services:

   #PHP Service with app
   php-fpm:
     build:
       context: .
       dockerfile: ./php-fpm/Dockerfile
     container_name: my-app-php-fpm
     user: 1000:1000
     mem_limit: 100m
     #restart: always
     working_dir: /application
     volumes:
       - ../:/application
       - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    #  ports:
    #    - "9000:9000"
     depends_on:
       - mysql

   #Nginx Service
   nginx:
     image: nginxinc/nginx-unprivileged:1.18-alpine
     container_name: my-webserver
     user: 1000:1000
     mem_limit: 100m
     working_dir: /application
     volumes:
       - ../:/application
       - ./nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
     ports:
       - "80:8080"
       #- "443:443"
     depends_on:
       - php-fpm

   #MySQL Service
   mysql:
     image: mysql:5.7.22
     container_name: my-mysql
     user: 1000:1000
     mem_limit: 500m
     #restart: always
     env_file:
       - ./dev.env
     volumes:
       - ./db_data:/var/lib/mysql
     ports:
       - "3306:3306"

